kind: pipeline
type: docker
name: pvoutput

steps:
- name: pytest
  image: python:3.8
  commands:
  - python3 -m pip install --quiet --upgrade pip
  - python3 -m pip install --quiet -r requirements-dev.txt
  - python3 -m pip install --quiet .
  - python3 -m pip install --quiet pytest
  - pytest
- name: testbuild
  image: python:3.8
  commands:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements-dev.txt
  - python3 -m pip install .
  - flit build
