kind: pipeline
type: docker
name: pvoutput

steps:
- name: pytest
  image: python:3.8
  commands:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install .
  - pip install pytest
  - pytest -k 'not test_configured_'
- name: testbuild
  image: python:3.8
  commands:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
  - flit build
