---
name: MKDocs Deployment to GitHub Pages

"on":
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  mkdocs:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to the repository
      pages: write    # Required to deploy to GitHub Pages
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Running mkdocs
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run mkdocs gh-deploy -m 'Commit {sha} MkDocs {version}'
